import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "ar" | "en";

export const translations = {
  ar: {
    dashboard: "لوحة التحكم",
    library: "المكتبة",
    futureSimulator: "محاكي المستقبل",
    leaderboard: "لوحة المتصدرين",
    influencers: "المؤثرون",
    admin: "الإدارة",
    adminNoor: "لوحة الإدارة",
    logout: "تسجيل الخروج",
    subscribe: "اشترك بـ 5$/شهر",
    logIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    searchLessons: "ابحث عن الدروس...",
    videoLibrary: "مكتبة الفيديوهات",
    videoLibraryDesc: "تصفح جميع الدروس مجاناً — فقط التشغيل والمعلم الذكي للمشتركين.",
    discussWithNoor: "ناقش الدرس مع نُور AI - أو اسأل مساعد الأستاذ الذكي",
    allCategories: "جميع الفئات",
    noVideos: "لم يتم العثور على فيديوهات",
    noVideosDesc: "لم نجد أي دروس تطابق بحثك. حاول تعديل البحث أو مسح الفلاتر.",
    clearFilters: "مسح الفلاتر",
    loading: "جاري التحميل...",
    langToggle: "English",
    lessonCheckpoints: "نقاط التحقق",
    noCheckpoints: "لا توجد نقاط تحقق لهذا الدرس.",
    checkpointReached: "نقطة تحقق",
    resumeVideo: "استئناف الفيديو",
    skipForNow: "تخطي الآن",
    typeAnswer: "اكتب إجابتك هنا...",
    greeting: "مرحباً",
    totalVideos: "إجمالي الفيديوهات",
    totalUsers: "إجمالي المستخدمين",
    subscribers: "المشتركون",
    videoManagement: "إدارة الفيديوهات",
    recentUsers: "المستخدمون الأخيرون",
    addVideo: "إضافة فيديو",
    videoTitle: "عنوان الفيديو",
    youtubeUrl: "رابط يوتيوب",
    category: "الفئة",
    save: "حفظ",
    saving: "جارٍ الحفظ...",
    delete: "حذف",
    confirmDelete: "هل أنت متأكد من الحذف؟",
    footerText: "جميع الحقوق محفوظة",
    grade: "الصف",
    subject: "المادة",
    subscribeTitle: "اشترك في نُور AI",
    subscribeDesc: "احصل على وصول غير محدود لجميع الدروس والميزات المميزة",
    payWithCrypto: "الدفع بالعملات المشفرة (USDT)",
    paymentPending: "في انتظار الدفع",
    paymentAddress: "عنوان المحفظة",
    copyAddress: "نسخ العنوان",
    addressCopied: "تم نسخ العنوان",
    priceMonth: "5 دولار / شهر",
    dashboardWelcome: "أهلاً وسهلاً",
    continueWatching: "متابعة المشاهدة",
    startLearning: "ابدأ التعلم",
    noProgress: "لم تبدأ أي دروس بعد",
    home: "الرئيسية",
    features: "المميزات",
    joinNoor: "انضم إلى نُور AI",
    menu: "القائمة",
    videosWatched: "فيديوهات تمت مشاهدتها",
    completedFully: "مكتملة بالكامل",
    timeLearned: "وقت التعلم",
    totalStudyTime: "إجمالي وقت الدراسة",
    currentStreak: "السلسلة الحالية",
    days: "أيام",
    keepItUp: "أحسنت! واصل!",
    subscription: "الاشتراك",
    active: "نشط",
    freeTier: "مجاني",
    upgradePremium: "ترقية إلى Premium",
    recentVideos: "الدروس الأخيرة",
    viewLibrary: "عرض المكتبة",
    noVideosWatched: "لم تشاهد أي دروس بعد",
    exploreLibrary: "استكشف المكتبة",
    startJourney: "ابدأ رحلتك التعليمية باستكشاف مكتبة الفيديوهات. سنتتبع تقدمك هنا.",
    continueBtn: "متابعة المشاهدة",
    refreshNotice: "يرجى تحديث الصفحة (Refresh) لرؤية أحدث الدروس والتحديثات",

    // ── Promo page ────────────────────────────────────────────
    promoBadge: "منصة تعليمية عربية متخصصة",
    promoH1: "منصة نُور AI",
    promoH1Sub: "دليلك الشامل للقدرات، التحصيلي، ونظام المسارات",
    promoHeroDesc: "مئات الدروس التعليمية وأكثر + مدرّس ذكاء اصطناعي سقراطي + محاكي المستقبل المهني — كل ما تحتاجه في مكان واحد، بـ 5$ شهرياً فقط.",
    promoCtaStart: "ابدأ مجاناً الآن",
    promoCtaPricing: "عرض الأسعار",

    promoStatLessons: "درس تعليمي",
    promoStatLessonsSub: "والقادم أكثر..",
    promoStatTracks: "مسارات تعليمية",
    promoStatTracksSub: "مع إضافة المزيد مستقبلاً",
    promoStatPrice: "فقط شهرياً",
    promoStatPriceSub: "وصول كامل غير محدود",

    promoCoursesBadge: "المكتبة التعليمية",
    promoCoursesH2: "مئات الدروس التعليمية وأكثر",
    promoCoursesDesc: "تغطية شاملة لكل ما تحتاجه — من القدرات والتحصيلي إلى مسارات الثانوية والنصائح الذهبية قبل الاختبار.",
    promoCoursesCta: "تصفّح المكتبة كاملاً",
    promoCatCountGrowing: "متنامٍ",
    promoCatCountRenewing: "متجددة",

    promoCatQuduratTitle: "قدرات",
    promoCatQuduratDesc: "دروس شاملة لاختبار القدرات العامة — لفظي وكمي — مع نقاط تحقق بالذكاء الاصطناعي تضمن الفهم الفعلي. والقادم أكثر..",
    promoCatTahsiliTitle: "تجميعات تحصيلي",
    promoCatTahsiliDesc: "تجميعات وشرح معمّق لاختبار التحصيل الدراسي — علوم وأدبيات — بأسلوب الطريقة السقراطية. والقادم أكثر..",
    promoCatSecondaryTitle: "دروس مسارات ثانوي",
    promoCatSecondaryDesc: "مسارات الثانوي الحالية — علمي وأدبي — معبّأة في دروس مركّزة وفعّالة، مع إضافة المزيد مستقبلاً.",
    promoCatGeneralTitle: "عام — نصائح ذهبية",
    promoCatGeneralDesc: "مجموعة متجددة من النصائح الذهبية قبل الامتحانات — محتوى يُعدّك نفسياً وذهنياً لتتفوق يوم الاختبار.",

    promoSocraticBadge: "المعلم السقراطي",
    promoSocraticH2: "نُور لا تعطيك الإجابة،",
    promoSocraticH2Span: "بل تضيء لك الطريق",
    promoSocraticH2End: "لتجدها بنفسك",
    promoSocraticDesc: "بدلاً من تلقّي المعلومة جاهزة، يدفعك المعلم الذكي في نُور AI نحو التفكير النقدي — بأسئلة موجَّهة تقودك خطوةً بخطوة حتى تصل للإجابة بنفسك وتثبت في ذاكرتك إلى الأبد.",
    promoSocraticFeat1: "حوار تفاعلي يحاكي أفضل المعلمين الخصوصيين",
    promoSocraticFeat2: "أسئلة موجَّهة بدلاً من إجابات جاهزة",
    promoSocraticFeat3: "فهم حقيقي يدوم — لا حفظ يتبخّر بعد الاختبار",
    promoSocraticCta: "جرّب المعلم السقراطي",
    promoSocraticQ1: "ما الذي يحدث للضغط عندما تزداد درجة الحرارة؟",
    promoSocraticA1: "أعتقد... يزداد؟ 🤔",
    promoSocraticQ2: "ممتاز! لماذا تعتقد ذلك؟ فكّر في قانون الغازات..",
    promoSocraticA2: "فهمت! P∝T عند ثبات الحجم ✅",
    promoSocraticQuote: "نُور تضيء لك الطريق لتجد الإجابة بنفسك",

    promoPauseBadge: "التوقف الذكي",
    promoPauseH2: "الفيديو يتوقف،",
    promoPauseH2Span: "ليسألك ويتفاعل معك",
    promoPauseDesc: "التوقف الذكي: نُور تضمن استيعابك لكل معلومة — الفيديو يتوقف عند نقاط محورية ليتحقق من فهمك قبل المتابعة، لا مجرد مشاهدة سلبية.",
    promoPauseFeat1: "توقف تلقائي عند كل نقطة تعليمية حاسمة",
    promoPauseFeat2: "سؤال فوري من المعلم الذكي يختبر استيعابك",
    promoPauseFeat3: "الفيديو لا يكمل إلا بعد التحقق من الفهم الفعلي",
    promoPauseCta: "جرّب التوقف الذكي",
    promoPauseLabel: "نُور تسألك:",
    promoPauseQuestion: "ما الفرق بين الكمي اللفظي والكمي العددي في اختبار القدرات؟",
    promoPauseOpt1: "أجب بنعم / لا",
    promoPauseOpt2: "فكّر ثم تابع",
    promoPauseCheck: "✓ تحقّق من الفهم",
    promoPauseBadgeText: "توقف ذكي ⏸",

    promoSimBadge: "مدعوم بالذكاء الاصطناعي",
    promoSimH2: "محاكي المستقبل المهني",
    promoSimDesc: "لطلاب الثانوي والجامعة — أجب على 4 أسئلة وسيرسم لك نُور AI خارطة طريق مهنية كاملة مع توقعات مالية حقيقية ومراحل عملية واضحة.",
    promoSimFeat1: "4 أسئلة فقط — نتيجة فورية ودقيقة",
    promoSimFeat2: "توقعات مالية حقيقية للمهن المُوصى بها",
    promoSimFeat3: "خارطة طريق مفصّلة بمراحل واضحة",
    promoSimFeat4: "تجربة مجانية مرة واحدة بدون اشتراك",
    promoSimCta: "جرّب المحاكي مجاناً",

    promoTipsBadge: "فئة عام",
    promoTipsH2: "نصائح ذهبية لما قبل الاختبار",
    promoTipsDesc: "في فئة عام تجد محتوى يُعدّك نفسياً وذهنياً — ليس فقط دراسياً — لتدخل الامتحان بأعلى مستوى من الاستعداد.",
    promoTipsDescStrong: "عام",
    promoTipsBoxTitle: "اشترك للوصول لمجموعتنا المتجددة من النصائح الذهبية في فئة عام",
    promoTipsBoxDesc: "من إدارة الوقت داخل قاعة الاختبار، إلى تقنيات حل الأسئلة المُركّبة — كل شيء موثّق بفيديوهات قصيرة ومركّزة.",
    promoTipsCta: "ابدأ التجربة المجانية",
    promoTip1: "ابدأ المراجعة قبل الامتحان بأسبوعين على الأقل",
    promoTip2: "حلّ نماذج حقيقية من أسئلة السنوات الماضية",
    promoTip3: "خصّص 20 دقيقة يومياً للمراجعة السريعة",
    promoTip4: "استخدم تقنية بومودورو: 25 دقيقة تركيز + 5 راحة",
    promoTip5: "نَم 8 ساعات قبل يوم الامتحان — الدماغ يحتاجها",
    promoTip6: "اكتب ما تعلّمته بأسلوبك الخاص — يُرسّخه في الذاكرة",

    promoFooterBadge: "بدون التزام — إلغاء في أي وقت",
    promoFooterH2: "ابدأ اليوم — تجربة مجانية متاحة",
    promoFooterDesc: "انضم إلى آلاف الطلاب الذين يستخدمون نُور AI للاستعداد للقدرات والتحصيلي ومسارات الثانوية.",
    promoFooterPrimary: "إنشاء حساب مجاني",
    promoFooterSecondary: "عرض الأسعار — 5$/شهر",
  },
  en: {
    dashboard: "Dashboard",
    library: "Library",
    futureSimulator: "Future Simulator",
    leaderboard: "Leaderboard",
    influencers: "Influencers",
    admin: "Admin",
    adminNoor: "Admin Panel",
    logout: "Log out",
    subscribe: "Subscribe $5/mo",
    logIn: "Log in",
    signUp: "Sign up",
    searchLessons: "Search lessons...",
    videoLibrary: "Video Library",
    videoLibraryDesc: "Browse all lessons freely — only Play & AI Tutor require subscription.",
    discussWithNoor: "Discuss with NOOR AI - or Ask the Smart Teacher",
    allCategories: "All Categories",
    noVideos: "No videos found",
    noVideosDesc: "We couldn't find any lessons matching your filters. Try adjusting your search or clearing filters.",
    clearFilters: "Clear Filters",
    loading: "Loading...",
    langToggle: "العربية",
    lessonCheckpoints: "Lesson Checkpoints",
    noCheckpoints: "No checkpoints set for this lesson.",
    checkpointReached: "Checkpoint",
    resumeVideo: "Resume Video",
    skipForNow: "Skip for now",
    typeAnswer: "Type your answer here...",
    greeting: "Hello",
    totalVideos: "Total Videos",
    totalUsers: "Total Users",
    subscribers: "Subscribers",
    videoManagement: "Video Management",
    recentUsers: "Recent Users",
    addVideo: "Add Video",
    videoTitle: "Video Title",
    youtubeUrl: "YouTube URL",
    category: "Category",
    save: "Save",
    saving: "Saving...",
    delete: "Delete",
    confirmDelete: "Are you sure you want to delete this video?",
    footerText: "All rights reserved",
    grade: "Grade",
    subject: "Subject",
    subscribeTitle: "Subscribe to NOOR AI",
    subscribeDesc: "Get unlimited access to all lessons and premium features",
    payWithCrypto: "Pay with Crypto (USDT)",
    paymentPending: "Awaiting Payment",
    paymentAddress: "Wallet Address",
    copyAddress: "Copy Address",
    addressCopied: "Address Copied",
    priceMonth: "$5 / month",
    dashboardWelcome: "Welcome back",
    continueWatching: "Continue Watching",
    startLearning: "Start Learning",
    noProgress: "You haven't started any lessons yet",
    home: "Home",
    features: "Features",
    joinNoor: "Join NOOR AI",
    menu: "Menu",
    videosWatched: "Videos Watched",
    completedFully: "completed fully",
    timeLearned: "Time Learned",
    totalStudyTime: "Total study time",
    currentStreak: "Current Streak",
    days: "days",
    keepItUp: "Keep it up!",
    subscription: "Subscription",
    active: "Active",
    freeTier: "Free Tier",
    upgradePremium: "Upgrade to Premium",
    recentVideos: "Recent Videos",
    viewLibrary: "View Library",
    noVideosWatched: "No videos watched yet",
    exploreLibrary: "Explore Library",
    startJourney: "Start your learning journey by exploring our video library. We'll track your progress here.",
    continueBtn: "Continue Watching",
    refreshNotice: "Please refresh the page to see the latest lessons and updates",

    // ── Promo page ────────────────────────────────────────────
    promoBadge: "Arabic-First Educational Platform",
    promoH1: "NOOR AI Platform",
    promoH1Sub: "Your Complete Guide to Qudurat, Tahsili & Secondary Tracks",
    promoHeroDesc: "Hundreds of lessons & more + Socratic AI Tutor + Career Future Simulator — everything you need in one place, for just $5/month.",
    promoCtaStart: "Start Free Now",
    promoCtaPricing: "View Pricing",

    promoStatLessons: "Lessons",
    promoStatLessonsSub: "and growing",
    promoStatTracks: "Learning Tracks",
    promoStatTracksSub: "with more on the way",
    promoStatPrice: "per month only",
    promoStatPriceSub: "unlimited full access",

    promoCoursesBadge: "Learning Library",
    promoCoursesH2: "Hundreds of Lessons & More",
    promoCoursesDesc: "Comprehensive coverage of everything you need — from Qudurat & Tahsili to Secondary Tracks and pre-exam golden tips.",
    promoCoursesCta: "Browse the Full Library",
    promoCatCountGrowing: "Growing",
    promoCatCountRenewing: "Updated",

    promoCatQuduratTitle: "Qudurat",
    promoCatQuduratDesc: "In-depth lessons for the General Aptitude Test — verbal and quantitative — with AI-powered comprehension checkpoints. And more to come.",
    promoCatTahsiliTitle: "Tahsili Collections",
    promoCatTahsiliDesc: "Comprehensive exam banks and deep-dive explanations for the Achievement Test — sciences and humanities — using the Socratic method. And more to come.",
    promoCatSecondaryTitle: "Secondary Tracks",
    promoCatSecondaryDesc: "Current secondary school tracks — Science and Arts — packed into focused, effective lessons, with more tracks added regularly.",
    promoCatGeneralTitle: "General — Golden Tips",
    promoCatGeneralDesc: "An ever-growing collection of pre-exam golden tips — content that prepares you mentally and psychologically to excel on test day.",

    promoSocraticBadge: "Socratic AI Tutor",
    promoSocraticH2: "NOOR doesn't give you the answer —",
    promoSocraticH2Span: "it lights the way",
    promoSocraticH2End: "for you to discover it yourself",
    promoSocraticDesc: "Instead of receiving ready-made answers, NOOR AI's intelligent tutor guides you toward critical thinking — through directed questions that lead you step by step until you reach the answer yourself, locking it into long-term memory.",
    promoSocraticFeat1: "Interactive dialogue that mirrors the best private tutors",
    promoSocraticFeat2: "Guided questions instead of ready-made answers",
    promoSocraticFeat3: "Genuine understanding that lasts — not memorisation that fades after the exam",
    promoSocraticCta: "Try Socratic AI Tutoring",
    promoSocraticQ1: "What happens to pressure as temperature increases?",
    promoSocraticA1: "I think... it increases? 🤔",
    promoSocraticQ2: "Great! Why do you think so? Think about the gas law..",
    promoSocraticA2: "Got it! P∝T at constant volume ✅",
    promoSocraticQuote: "NOOR lights the way for you to discover the answer yourself",

    promoPauseBadge: "Interactive Smart Pause",
    promoPauseH2: "The video pauses —",
    promoPauseH2Span: "to quiz and engage with you",
    promoPauseDesc: "Smart Pause: NOOR ensures you absorb every piece of information — the video stops at pivotal points to verify comprehension before continuing. No more passive watching.",
    promoPauseFeat1: "Automatic pause at every critical learning checkpoint",
    promoPauseFeat2: "Instant question from the AI tutor to test your understanding",
    promoPauseFeat3: "Video only resumes after real comprehension is confirmed",
    promoPauseCta: "Try Smart Pause",
    promoPauseLabel: "NOOR asks:",
    promoPauseQuestion: "What is the difference between verbal and numerical quantitative sections in the Qudurat exam?",
    promoPauseOpt1: "Answer Yes / No",
    promoPauseOpt2: "Think then continue",
    promoPauseCheck: "✓ Comprehension Check",
    promoPauseBadgeText: "Smart Pause ⏸",

    promoSimBadge: "Powered by Artificial Intelligence",
    promoSimH2: "Career Future Simulator",
    promoSimDesc: "For secondary and university students — answer 4 questions and NOOR AI will draw you a complete career roadmap with real salary projections and clear, actionable milestones.",
    promoSimFeat1: "Just 4 questions — instant, accurate results",
    promoSimFeat2: "Real salary projections for recommended careers",
    promoSimFeat3: "Detailed roadmap with clear milestones",
    promoSimFeat4: "One free trial — no subscription required",
    promoSimCta: "Try the Simulator Free",

    promoTipsBadge: "General Category",
    promoTipsH2: "Golden Tips for Pre-Exam Preparation",
    promoTipsDesc: "In the General category you'll find content that prepares you mentally and psychologically — not just academically — to enter the exam at peak readiness.",
    promoTipsDescStrong: "General",
    promoTipsBoxTitle: "Subscribe to access our ever-growing collection of Golden Tips in the General category",
    promoTipsBoxDesc: "From time management inside the exam hall, to techniques for solving complex multi-part questions — all documented in short, focused videos.",
    promoTipsCta: "Start Your Free Trial",
    promoTip1: "Begin your review at least two weeks before the exam",
    promoTip2: "Solve real past-year exam papers and question banks",
    promoTip3: "Dedicate 20 minutes daily to rapid review sessions",
    promoTip4: "Use the Pomodoro technique: 25 min focus + 5 min break",
    promoTip5: "Sleep 8 hours the night before the exam — your brain needs it",
    promoTip6: "Write what you've learned in your own words — it cements it in memory",

    promoFooterBadge: "No commitment — cancel anytime",
    promoFooterH2: "Start Today — Free Trial Available",
    promoFooterDesc: "Join thousands of students using NOOR AI to prepare for Qudurat, Tahsili, and Secondary Track exams.",
    promoFooterPrimary: "Create Free Account",
    promoFooterSecondary: "View Pricing — $5/month",
  }
};

export const DEFAULT_CATEGORIES = [
  { value: "Qudurat", labelAr: "قدرات", labelEn: "Qudurat" },
  { value: "Tahsili", labelAr: "تحصيلي", labelEn: "Tahsili" },
  { value: "Secondary", labelAr: "ثانوي - مسارات", labelEn: "Secondary - Tracks" },
  { value: "General", labelAr: "عام", labelEn: "General" },
];

export function getCategoryLabel(value: string, lang: "ar" | "en"): string {
  const cat = DEFAULT_CATEGORIES.find(c => c.value === value);
  if (cat) return lang === "ar" ? cat.labelAr : cat.labelEn;
  return value;
}

interface LangContextType {
  lang: Lang;
  t: typeof translations.ar;
  toggle: () => void;
}

const LangContext = createContext<LangContextType>({
  lang: "ar",
  t: translations.ar,
  toggle: () => {},
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("ar");
  const toggle = () => setLang(l => (l === "ar" ? "en" : "ar"));

  return (
    <LangContext.Provider value={{ lang, t: translations[lang], toggle }}>
      <div dir={lang === "ar" ? "rtl" : "ltr"} lang={lang} className="contents">
        {children}
      </div>
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
